# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InterfaceLocker
                                 A QGIS plugin
 Blocca/ripristina interfaccia QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-07
        copyright            : (C) 2025 by dr. geol. Faustino Cetraro
        email                : geol-faustino@libero.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load InterfaceLocker class from file InterfaceLocker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .interface_locker import InterfaceLocker
    return InterfaceLocker(iface)
